In [1]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier  # Import RandomForestClassifier (New)
import pandas as pd
import time
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
import cv2 as cv
from keras.models import Sequential
from keras.layers import Dense
x



mnist = fetch_openml('mnist_784', version=1, cache=True, as_frame=False)

X = mnist["data"]
y = mnist["target"].astype(np.uint8)
Z = mnist["feature_names"]
A = mnist["target_names"]
F = mnist["DESCR"]
O = mnist["details"]
B = mnist["frame"]
N = mnist["categories"]
M = mnist["url"]

print(type(mnist))
for key in mnist.keys():


    
    print(key)

<class 'sklearn.utils._bunch.Bunch'>
data
target
frame
categories
feature_names
target_names
DESCR
details
url


In [2]:
X = X[:70000]
y = y[:70000]

In [3]:
start = time.time()
###print(y[:10])

svm_model = SVC(kernel='rbf', random_state=42)
###  data and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_scaled = X_train / 255
X_test_scaled = X_test / 255
svm_model.fit(X_train_scaled, y_train)

y_pred = svm_model.predict(X_test_scaled)


# Model evaluatation
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy * 100)

stop  = time.time()
print("im am done, i took ",stop - start, "seconds"  )


#untill accuarsy is at 97% dont stop. 



Accuracy: 97.64285714285714
im am done, i took  256.5903944969177 seconds


In [4]:
# Start timing
start_rf = time.time()

# creates and train Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled, y_train)

# predicts with Random Forest Classifier
y_pred_rf = rf_model.predict(X_test_scaled)

# Model evaluation for Random Forest Classifier
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Classifier Accuracy:", accuracy_rf * 100)

# Stop timing and print the time taken
stop_rf = time.time()
print("Random Forest Classifier training complete in", stop_rf - start_rf, "seconds")

Random Forest Classifier Accuracy: 96.75
Random Forest Classifier training complete in 35.10923361778259 seconds


In [5]:
conf_matrix_svm = confusion_matrix(y_test, y_pred)

# Compute precision, recall, and F1-score for SVM
precision_svm = precision_score(y_test, y_pred, average='weighted')
recall_svm = recall_score(y_test, y_pred, average='weighted')
f1_svm = f1_score(y_test, y_pred, average='weighted')

# Compute confusion matrix for Random Forest Classifier
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

# Compute precision, recall, and F1-score for Random Forest Classifier
precision_rf = precision_score(y_test, y_pred_rf, average='weighted')
recall_rf = recall_score(y_test, y_pred_rf, average='weighted')
f1_rf = f1_score(y_test, y_pred_rf, average='weighted')

print("Confusion Matrix for SVM:")
print(conf_matrix_svm)
print("Precision for SVM:", precision_svm)
print("Recall for SVM:", recall_svm)
print("F1-score for SVM:", f1_svm)
print("\n")

print("Confusion Matrix for Random Forest Classifier:")
print(conf_matrix_rf)
print("Precision for Random Forest Classifier:", precision_rf)
print("Recall for Random Forest Classifier:", recall_rf)
print("F1-score for Random Forest Classifier:", f1_rf)

Confusion Matrix for SVM:
[[1329    1    3    0    1    2    2    1    4    0]
 [   0 1585    4    3    2    0    0    4    2    0]
 [   3    4 1348    2    3    2    4    8    5    1]
 [   0    2   11 1386    2   11    1    9    7    4]
 [   1    0    2    0 1269    0    3    2    2   16]
 [   0    1    2   15    2 1236    9    1    7    0]
 [   1    0    0    0    4    4 1384    0    3    0]
 [   1    6   12    1    5    1    0 1465    1   11]
 [   2    6    8   12    4    9    6    4 1303    3]
 [   5    8    2    8   14    2    0   11    5 1365]]
Precision for SVM: 0.9764205434434183
Recall for SVM: 0.9764285714285714
F1-score for SVM: 0.97640708117749


Confusion Matrix for Random Forest Classifier:
[[1325    0    4    0    1    1    3    1    6    2]
 [   0 1573    6    8    2    0    0    6    3    2]
 [   3    5 1335    4    5    1    9    8    8    2]
 [   1    0   23 1366    0    9    0   14   12    8]
 [   4    1    3    0 1256    0    2    3    3   23]
 [   1    3    3   17

In [6]:
#model = tf.keras.models.load_model("C:/Users/A551110/PycharmProjects/keras_mnist/venv/mnistv2.model")
#file = "C:/Users/A551110/Documents/images/7.png"
#model.evaluate(x_test, y_test)

#image = cv.imread(file, cv.IMREAD_GRAYSCALE)
#image = cv.resize(image, (28,28))
#image = 255-image          #inverts image. Always gets read inverted.

#plt.imshow(image.reshape(28, 28),cmap='Greys')
#plt.show()
#pred = model.predict(image.reshape(1, 28, 28, 1), batch_size=1)

#print(pred.argmax())

In [7]:

keras = Sequential([
    Dense(units = 128, activation='relu',input_shape =(784,) ),
    Dense(units = 64, activation='relu' ),
     Dense(units = 10, activation='softmax' )

    
])
keras.compile(loss='sparse_categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])
keras_accuracy = keras.evaluate(X_test, y_test)
print(type(keras_accuracy))
for x in keras_accuracy:
    print(x)
    

C:\Users\gabej\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


438/438 ━━━━━━━━━━━━━━━━━━━━ 1s 796us/step - accuracy: 0.0945 - loss: 199.8279
<class 'list'>
199.61436462402344
0.0949285700917244
